DATASETS:
  NAME: "MFdataset"
  DIR : "./datasets/MFdataset/" 
  IMS_PER_BATCH: &b 14
  WORKERS_PER_GPU: 4
MODEL:
  META_ARCHITECTURE: "RGBTMaskFormer"
  BACKBONE:
    NAME: "RGBT_D2SwinTransformer"
  FUSION:
    AGGREGATION: "MAX" # "ADD" "MAX" "ATT_CS"  "ATT_AGG"
    LAYER: ["res2", "res3", "res4", "res5"]
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    SHARE_START_IDX : 4 # 0 is all shared between RGB and thermal backbones except proj layer, 4 is not shared at all.
  WEIGHTS: "pretrained/swin_small_patch4_window7_224.pkl" # ImageNet 1K pre-trained
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 9
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # NORM: "SyncBN" 
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "MultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
  PIXEL_MEAN: [123.675, 116.280, 103.530, 127]
  PIXEL_STD: [58.395, 57.120, 57.375, 60]
  CRMLOSS:
    MWS_WEIGHT: 1.0
    SDC_WEIGHT: 1.0
    SDN_WEIGHT: 1.0
SOLVER:
  IMS_PER_BATCH: *b
  BASE_LR: 0.0001
  MAX_ITER: 35000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.05 
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 480) for x in range(5, 21)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 480
  MAX_SIZE_TRAIN: 1920
  MAX_SIZE_TEST: 960
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (240, 320)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  MASK:
    ENABLED: True
    SIZE: (256, 320)
    PATCH_SIZE: 32
    RATIO: 0.5
    TYPE: 'patch' # 'patch', 'square'
    STRATEGY : 'rand_comp' # comp, rand_comp, indiv
  SIZE_DIVISIBILITY: -1
  FORMAT: "RGBT"
  DATASET_MAPPER_NAME: "mask_former_semantic"
SAVE:
  DIR_ROOT: "./results_MF"
  DIR_NAME: "RGBT_former"
  FLAG_VIS_GT: False