name: CRM
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - cudatoolkit=11.3.1=h9edb442_11
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=hca18f0e_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - icu=72.1=hcb278e6_0
  - jpeg=9e=h0b41bf4_3
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libdeflate=1.17=h0b41bf4_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libhwloc=2.9.0=hd6dc26d_0
  - libiconv=1.17=h166bdaf_0
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.39=h753d276_0
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.44.2=h166bdaf_0
  - libwebp-base=1.3.0=h0b41bf4_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.3=hfdac1af_6
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=16.0.0=h417c0b6_0
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - ncurses=6.3=h27087fc_1
  - nettle=3.6=he412f7d_0
  - numpy=1.23.5=py39h14f4228_0
  - numpy-base=1.23.5=py39h31eccc5_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.0=h0b41bf4_0
  - pillow=9.4.0=py39h2320bf1_1
  - pip=23.0.1=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.9.16=h2782a2a_0_cpython
  - python_abi=3.9=3_cp39
  - pytorch=1.10.1=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h8228510_1
  - six=1.16.0=pyh6c4a22f_0
  - tbb=2021.8.0=hf52228f_0
  - tk=8.6.12=h27826a3_0
  - torchvision=0.11.2=py39_cu113
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023b=h71feb2d_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
  - pip:
      - absl-py==1.4.0
      - addict==2.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - async-timeout==4.0.2
      - attrs==22.2.0
      - black==21.4b2
      - cachetools==5.3.0
      - certifi==2022.12.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cloudpickle==2.2.1
      - contourpy==1.0.7
      - cycler==0.11.0
      - detectron2==0.6+cu113
      - filelock==3.10.7
      - fonttools==4.39.2
      - frozenlist==1.3.3
      - fsspec==2023.3.0
      - future==0.18.3
      - fvcore==0.1.5.post20221221
      - google-auth==2.16.3
      - google-auth-oauthlib==0.4.6
      - grpcio==1.53.0
      - huggingface-hub==0.13.3
      - hydra-core==1.3.2
      - idna==3.4
      - imageio==2.27.0
      - importlib-metadata==6.1.0
      - importlib-resources==5.12.0
      - iopath==0.1.9
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - lightning-utilities==0.8.0
      - markdown==3.4.3
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - mmcv==1.7.1
      - multidict==6.0.4
      - multiscaledeformableattention==1.0
      - mypy-extensions==1.0.0
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.7.0.72
      - packaging==23.0
      - pathspec==0.11.1
      - portalocker==2.7.0
      - protobuf==4.22.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycocotools==2.0.6
      - pydot==1.4.2
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytorch-lightning==1.9.2
      - pyyaml==6.0
      - regex==2023.3.23
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - setuptools==59.5.0
      - tabulate==0.9.0
      - tensorboard==2.12.0
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.2.0
      - threadpoolctl==3.1.0
      - timm==0.6.13
      - toml==0.10.2
      - torchmetrics==0.11.4
      - tqdm==4.65.0
      - urllib3==1.26.15
      - werkzeug==2.2.3
      - yacs==0.1.8
      - yapf==0.32.0
      - yarl==1.8.2
      - zipp==3.15.0
prefix: /home/miruware/anaconda3/envs/CRM
